<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEW5u3qP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEW5u3qP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEW5u3qP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEW5u3qP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEW5u3qP\App_KernelDevDebugContainer([
    'container.build_hash' => 'EW5u3qP',
    'container.build_id' => '3c207275',
    'container.build_time' => 1712581729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEW5u3qP');
