<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3IDzsmf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3IDzsmf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3IDzsmf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3IDzsmf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3IDzsmf\App_KernelDevDebugContainer([
    'container.build_hash' => '3IDzsmf',
    'container.build_id' => '2e3f8a5d',
    'container.build_time' => 1712321927,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3IDzsmf');
