<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAp9vYiL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAp9vYiL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAp9vYiL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAp9vYiL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAp9vYiL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ap9vYiL',
    'container.build_id' => '337dac52',
    'container.build_time' => 1712130293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAp9vYiL');
